### PR TITLE
feat: add formatter and models

### PR DESCRIPTION
**Pull request by marianfoo**
## Description
Adding `models.ts` and `formatter.ts` otherwise the js files from main template is used

## Changes

- added  `models.ts` and `formatter.ts` from https://github.com/ui5-community/generator-ui5-ts-app-fcl/tree/main/generators/app/templates/src/model
- added `this.setModel(models.createDeviceModel(), "device");` in `Component.ts`

### CODE REVIEW

**Comment by petermuessig** [comment]
Cc @akudev - FYI, this is indeed a good extension to the template. 

@marianfoo : maybe we should also use the formatter and the model somewhere?

**Comment by marianfoo** [comment]
@petermuessig 
added the formatter to the `Main.controller`
the model is already used in the `Component`

**Comment by marianfoo** [comment]
@petermuessig @akudev 
all good here?

**Comment by akudev** [comment]
I'm not really taking care of this app generator. Maybe @petermuessig
 can have a look.

**Comment by marianfoo** [comment]
@petermuessig can I merge?

**Comment by petermuessig** [comment]
@marianfoo I discussed this with @akudev and we keep that change open till after UI5con since it would alter the generated output: https://github.com/SAP-samples/ui5-typescript-tutorial

**Comment by marianfoo** [comment]
> @marianfoo I discussed this with @akudev and we keep that change open till after UI5con since it would alter the generated output: https://github.com/SAP-samples/ui5-typescript-tutorial

all good here?
any changes?

**Comment by akudev** [comment]
@marianfoo I'd suggest to merge this as soon as the [fork/copy of the template](https://github.com/SAP-samples/ui5-typescript-tutorial/commit/13d81492a15e8992d0cd657872345becd37ddad2) in the tutorial repo is fully functional and its usage within the tutorial flow is documented. Then this template is decoupled from the tutorial and can be changed in any way.

**Comment by akudev** [comment]
From my perspective this PR can be merged now. But I'm not considering myself maintainer here, so @petermuessig ?

**Review by petermuessig — APPROVED** [review]
LGTM

**Pull request merged**
